start_date = 2024-01-01
end_date = 2024-01-01
parallelize = true
concurrent_threads = 6

[solvers.cbc]
name = "cbc"
executable = "solvers/cbc.exe"
persistent = false

[algorithms.maximize_ev]
run = true
salary = 50_000
solver = "cbc"

[algorithms.maximize_ev_sampler]
run = false
salary = 50_000
projection_cutoff = 5
sample_size = 5
solver = "cbc"

[algorithms.maximize_ev_multiple_sampler]
run = false
salary = 50_000
projection_cutoff = 5
sample_size = 5
desired_lineups = 3
solver = "cbc"

[algorithms.random_sampler]
run = false
